name: Deploy to Firebase Hosting on merge

on:
  pull_request:
    types: [closed, labeled]
    branches:
      - master
jobs:
  build_and_deploy:
    if: github.event.label.name == 'enhancement'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - uses: actions/checkout@v3
      - run: npm install && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_THESIS_BENG }}'
          channelId: live
          projectId: thesis-beng
          entryPoint: ./app
